### ISSUE TITLE
Geoff Restarted Today's Poll

### ISSUE THREAD

**Issue by josh-justjosh** [davwheat/world-cup-of-tocs#15]
Geoff has restarted today's poll [here](https://twitter.com/geofftech/status/1352897209583472640) so the poll tracker is currently looking at a dead poll

**Comment by Gum-Joe** [comment]
Thanks, we are aware of this issue...
...except we have no capacity to fix it right now, as I at least don't have a computer to fix it with.

Given this has happened twice we should probably build some resilience into the system...
